// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP7z374YIqi4MxvhwIlBqEwYaGwQtmLMQ',
    appId: '1:140292343446:web:c308a47e3af5aeaf9fa4b7',
    messagingSenderId: '140292343446',
    projectId: 'osteria-romagnola',
    authDomain: 'osteria-romagnola.firebaseapp.com',
    storageBucket: 'osteria-romagnola.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ymo_BlI-MrGOs8f573KkGwniIK5zAVA',
    appId: '1:140292343446:android:35c59e5b2016d9869fa4b7',
    messagingSenderId: '140292343446',
    projectId: 'osteria-romagnola',
    storageBucket: 'osteria-romagnola.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaA1ji3Ks8XTJ1fCMX37pr2stpNPIVMP8',
    appId: '1:140292343446:ios:d154f4746955dfb49fa4b7',
    messagingSenderId: '140292343446',
    projectId: 'osteria-romagnola',
    storageBucket: 'osteria-romagnola.firebasestorage.app',
    iosBundleId: 'com.example.osteriaRomagnola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaA1ji3Ks8XTJ1fCMX37pr2stpNPIVMP8',
    appId: '1:140292343446:ios:d154f4746955dfb49fa4b7',
    messagingSenderId: '140292343446',
    projectId: 'osteria-romagnola',
    storageBucket: 'osteria-romagnola.firebasestorage.app',
    iosBundleId: 'com.example.osteriaRomagnola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP7z374YIqi4MxvhwIlBqEwYaGwQtmLMQ',
    appId: '1:140292343446:web:18e2f01b35b091b59fa4b7',
    messagingSenderId: '140292343446',
    projectId: 'osteria-romagnola',
    authDomain: 'osteria-romagnola.firebaseapp.com',
    storageBucket: 'osteria-romagnola.firebasestorage.app',
  );
}
